/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.hqbhoho.bigdata.learnKafka.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Account extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2979859593234508185L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Account\",\"namespace\":\"com.hqbhoho.bigdata.learnKafka.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"account\",\"type\":\"double\"},{\"name\":\"eventTime\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public double account;
  @Deprecated public long eventTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Account() {}

  /**
   * All-args constructor.
   */
  public Account(java.lang.CharSequence name, java.lang.Double account, java.lang.Long eventTime) {
    this.name = name;
    this.account = account;
    this.eventTime = eventTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return account;
    case 2: return eventTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: account = (java.lang.Double)value$; break;
    case 2: eventTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'account' field.
   */
  public java.lang.Double getAccount() {
    return account;
  }

  /**
   * Sets the value of the 'account' field.
   * @param value the value to set.
   */
  public void setAccount(java.lang.Double value) {
    this.account = value;
  }

  /**
   * Gets the value of the 'eventTime' field.
   */
  public java.lang.Long getEventTime() {
    return eventTime;
  }

  /**
   * Sets the value of the 'eventTime' field.
   * @param value the value to set.
   */
  public void setEventTime(java.lang.Long value) {
    this.eventTime = value;
  }

  /**
   * Creates a new Account RecordBuilder.
   * @return A new Account RecordBuilder
   */
  public static com.hqbhoho.bigdata.learnKafka.avro.Account.Builder newBuilder() {
    return new com.hqbhoho.bigdata.learnKafka.avro.Account.Builder();
  }
  
  /**
   * Creates a new Account RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Account RecordBuilder
   */
  public static com.hqbhoho.bigdata.learnKafka.avro.Account.Builder newBuilder(com.hqbhoho.bigdata.learnKafka.avro.Account.Builder other) {
    return new com.hqbhoho.bigdata.learnKafka.avro.Account.Builder(other);
  }
  
  /**
   * Creates a new Account RecordBuilder by copying an existing Account instance.
   * @param other The existing instance to copy.
   * @return A new Account RecordBuilder
   */
  public static com.hqbhoho.bigdata.learnKafka.avro.Account.Builder newBuilder(com.hqbhoho.bigdata.learnKafka.avro.Account other) {
    return new com.hqbhoho.bigdata.learnKafka.avro.Account.Builder(other);
  }
  
  /**
   * RecordBuilder for Account instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Account>
    implements org.apache.avro.data.RecordBuilder<Account> {

    private java.lang.CharSequence name;
    private double account;
    private long eventTime;

    /** Creates a new Builder */
    private Builder() {
      super(com.hqbhoho.bigdata.learnKafka.avro.Account.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hqbhoho.bigdata.learnKafka.avro.Account.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.account)) {
        this.account = data().deepCopy(fields()[1].schema(), other.account);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTime)) {
        this.eventTime = data().deepCopy(fields()[2].schema(), other.eventTime);
        fieldSetFlags()[2] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Account instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hqbhoho.bigdata.learnKafka.avro.Account other) {
            super(com.hqbhoho.bigdata.learnKafka.avro.Account.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.account)) {
        this.account = data().deepCopy(fields()[1].schema(), other.account);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTime)) {
        this.eventTime = data().deepCopy(fields()[2].schema(), other.eventTime);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.hqbhoho.bigdata.learnKafka.avro.Account.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.hqbhoho.bigdata.learnKafka.avro.Account.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'account' field.
      * @return The value.
      */
    public java.lang.Double getAccount() {
      return account;
    }

    /**
      * Sets the value of the 'account' field.
      * @param value The value of 'account'.
      * @return This builder.
      */
    public com.hqbhoho.bigdata.learnKafka.avro.Account.Builder setAccount(double value) {
      validate(fields()[1], value);
      this.account = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'account' field has been set.
      * @return True if the 'account' field has been set, false otherwise.
      */
    public boolean hasAccount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'account' field.
      * @return This builder.
      */
    public com.hqbhoho.bigdata.learnKafka.avro.Account.Builder clearAccount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTime' field.
      * @return The value.
      */
    public java.lang.Long getEventTime() {
      return eventTime;
    }

    /**
      * Sets the value of the 'eventTime' field.
      * @param value The value of 'eventTime'.
      * @return This builder.
      */
    public com.hqbhoho.bigdata.learnKafka.avro.Account.Builder setEventTime(long value) {
      validate(fields()[2], value);
      this.eventTime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'eventTime' field has been set.
      * @return True if the 'eventTime' field has been set, false otherwise.
      */
    public boolean hasEventTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventTime' field.
      * @return This builder.
      */
    public com.hqbhoho.bigdata.learnKafka.avro.Account.Builder clearEventTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Account build() {
      try {
        Account record = new Account();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.account = fieldSetFlags()[1] ? this.account : (java.lang.Double) defaultValue(fields()[1]);
        record.eventTime = fieldSetFlags()[2] ? this.eventTime : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
